import Foundation

/// Priority level for coaching insights (lower number = higher priority)
enum InsightPriority: Int, Sendable, Comparable, Hashable {
    case critical = 1    // P1: Recovery warning, overtraining
    case high = 2        // P2: Sleep debt, high fatigue
    case medium = 3      // P3: Muscle fatigue advisory
    case standard = 4    // P4: Goal proximity
    case low = 5         // P5: Positive trends
    case info = 6        // P6: Negative trends
    case ambient = 7     // P7: Activity gaps
    case celebration = 8 // P8: PR, milestones
    case fallback = 9    // P9: Default condition-based

    static func < (lhs: InsightPriority, rhs: InsightPriority) -> Bool {
        lhs.rawValue < rhs.rawValue
    }
}

/// Category of a coaching insight
enum InsightCategory: String, Sendable, Hashable {
    case recovery
    case training
    case sleep
    case motivation
    case recap
    case weather
    case general
}

/// A coaching insight generated by the CoachingEngine
struct CoachingInsight: Sendable, Identifiable, Hashable {
    let id: String
    let priority: InsightPriority
    let category: InsightCategory
    let title: String
    let message: String
    let iconName: String
    /// Optional hint for navigation action (e.g., "startWorkout", "sleepDetail")
    let actionHint: String?

    init(
        id: String,
        priority: InsightPriority,
        category: InsightCategory,
        title: String,
        message: String,
        iconName: String,
        actionHint: String? = nil
    ) {
        self.id = id
        self.priority = priority
        self.category = category
        self.title = title
        self.message = message
        self.iconName = iconName
        self.actionHint = actionHint
    }
}
