import Foundation

/// Weekly or monthly workout summary report with aggregated statistics.
struct WorkoutReport: Sendable {
    let period: Period
    let startDate: Date
    let endDate: Date
    let stats: Stats
    let muscleBreakdown: [MuscleGroupStat]
    let highlights: [Highlight]
    /// Natural language summary generated by Foundation Models (or template fallback).
    let formattedSummary: String?

    enum Period: String, Sendable {
        case weekly
        case monthly

        var displayName: String {
            switch self {
            case .weekly: String(localized: "Weekly Report")
            case .monthly: String(localized: "Monthly Report")
            }
        }
    }

    struct Stats: Sendable {
        let totalSessions: Int
        let totalVolume: Double
        let totalDuration: Int
        let activeDays: Int
        let averageIntensity: Double
        /// Volume change vs previous period (-1.0 to +∞).
        let volumeChangePercent: Double?
    }

    struct MuscleGroupStat: Sendable, Identifiable {
        var id: MuscleGroup { muscleGroup }
        let muscleGroup: MuscleGroup
        let volume: Double
        let sessions: Int
    }

    struct Highlight: Sendable, Identifiable {
        let id = UUID()
        let type: HighlightType
        let description: String
    }

    enum HighlightType: String, Sendable {
        case personalRecord
        case streak
        case volumeIncrease
        case consistency
        case newExercise
    }
}
