import Foundation

extension WorkoutActivityType {

    /// SF Symbol name for the activity type.
    /// Shared between iOS and Watch targets.
    var iconName: String {
        switch self {
        case .running: "figure.run"
        case .walking: "figure.walk"
        case .cycling: "figure.outdoor.cycle"
        case .swimming: "figure.pool.swim"
        case .hiking: "figure.hiking"
        case .yoga: "figure.yoga"
        case .traditionalStrengthTraining: "dumbbell.fill"
        case .functionalStrengthTraining: "figure.strengthtraining.functional"
        case .highIntensityIntervalTraining: "figure.highintensity.intervaltraining"
        case .elliptical: "figure.elliptical"
        case .rowing: "figure.rower"
        case .coreTraining: "figure.core.training"
        case .flexibility: "figure.flexibility"
        case .socialDance, .cardioDance: "figure.dance"
        case .pilates: "figure.pilates"
        case .boxing: "figure.boxing"
        case .martialArts: "figure.martial.arts"
        case .wrestling: "figure.wrestling"
        case .kickboxing: "figure.kickboxing"
        case .fencing: "figure.fencing"
        case .basketball: "figure.basketball"
        case .soccer: "figure.soccer"
        case .tennis: "figure.tennis"
        case .badminton: "figure.badminton"
        case .tableTennis: "figure.table.tennis"
        case .volleyball: "figure.volleyball"
        case .baseball: "figure.baseball"
        case .softball: "figure.softball"
        case .americanFootball: "figure.american.football"
        case .rugby: "figure.rugby"
        case .hockey: "figure.hockey"
        case .lacrosse: "figure.lacrosse"
        case .cricket: "figure.cricket"
        case .handball: "figure.handball"
        case .racquetball: "figure.racquetball"
        case .squash: "figure.squash"
        case .pickleball: "figure.pickleball"
        case .bowling: "figure.bowling"
        case .golf: "figure.golf"
        case .discSports: "figure.disc.sports"
        case .australianFootball: "figure.australian.football"
        case .gymnastics: "figure.gymnastics"
        case .paddleSports: "oar.2.crossed"
        case .surfingSports: "figure.surfing"
        case .waterFitness: "figure.water.fitness"
        case .waterPolo: "figure.waterpolo"
        case .waterSports: "figure.water.fitness"
        case .sailing: "sailboat.fill"
        case .downhillSkiing: "figure.skiing.downhill"
        case .snowboarding: "figure.snowboarding"
        case .crossCountrySkiing: "figure.skiing.crosscountry"
        case .snowSports: "snowflake"
        case .skating: "figure.skating"
        case .climbing: "figure.climbing"
        case .mountaineering: "mountain.2.fill"
        case .equestrianSports: "figure.equestrian.sports"
        case .fishing: "figure.fishing"
        case .hunting: "scope"
        case .archery: "figure.archery"
        case .trackAndField: "figure.track.and.field"
        case .curling: "figure.curling"
        case .jumpRope: "figure.jumprope"
        case .stairClimbing: "figure.stairs"
        case .stairStepper: "figure.stair.stepper"
        case .stepTraining: "figure.step.training"
        case .mixedCardio: "figure.mixed.cardio"
        case .crossTraining: "figure.cross.training"
        case .handCycling: "figure.hand.cycling"
        case .taiChi: "figure.taichi"
        case .mindAndBody: "figure.mind.and.body"
        case .barre: "figure.barre"
        case .cooldown: "figure.cooldown"
        case .preparationAndRecovery: "figure.cooldown"
        case .swimBikeRun: "figure.open.water.swim"
        case .transition: "arrow.triangle.2.circlepath"
        case .fitnessGaming: "gamecontroller.fill"
        case .play: "figure.play"
        case .underwaterDiving: "water.waves"
        case .wheelchairRunPace: "figure.roll.runningpace"
        case .wheelchairWalkPace: "figure.roll"
        case .other: "figure.mixed.cardio"
        }
    }
}
