name: DUNE
options:
  bundleIdPrefix: com.raftel
  developmentLanguage: en
  deploymentTarget:
    iOS: "26.0"
    watchOS: "26.0"
  xcodeVersion: "26.2"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    IPHONEOS_DEPLOYMENT_TARGET: "26.0"
    DEVELOPMENT_TEAM: "4GWU9QB2JZ"
    CODE_SIGN_IDENTITY: "iPhone Developer"

schemes:
  DUNE:
    build:
      targets:
        DUNE: all
        DUNEWatch: all
        DUNETests: [test]
        DUNEUITests: [test]
    test:
      targets:
        - DUNETests
        - DUNEUITests

  DUNETests:
    build:
      targets:
        DUNE: all
        DUNETests: [test]
    test:
      targets:
        - DUNETests

  DUNEWatch:
    build:
      targets:
        DUNEWatch: all

targets:
  DUNE:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Data
      - path: Domain
      - path: Presentation
      - path: Resources
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/DUNE.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.raftel.dailve
        PRODUCT_NAME: DUNE
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "0.1.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: DUNE
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_NSHealthShareUsageDescription: "DUNE needs access to your health data to calculate condition scores and track your fitness progress."
        INFOPLIST_KEY_NSHealthUpdateUsageDescription: "DUNE may write workout and body composition data to Health."
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "DUNE uses your location to show current weather conditions for exercise planning."
    entitlements:
      path: Resources/DUNE.entitlements
      properties:
        aps-environment: development
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
        com.apple.developer.healthkit.background-delivery: true
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.raftel.dailve
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.ubiquity-kvstore-identifier: "$(TeamIdentifierPrefix)$(CFBundleIdentifier)"
    dependencies:
      - sdk: HealthKit.framework
      - sdk: CoreLocation.framework
      - target: DUNEWatch
        embed: true

  DUNEWatch:
    type: application
    platform: watchOS
    sources:
      - path: ../DUNEWatch
        excludes:
          - "Resources/**"
      - path: ../DUNEWatch/Resources
      # Shared SwiftData models
      - path: Data/Persistence/Models
        group: Shared/Models
      - path: Data/Persistence/Migration
        group: Shared/Migration
      # Shared Domain enums (required by @Model files)
      - path: Domain/Models/ExerciseCategory.swift
        group: Shared/Domain
      - path: Domain/Models/MuscleGroup.swift
        group: Shared/Domain
      - path: Domain/Models/Equipment.swift
        group: Shared/Domain
      - path: Domain/Models/ExerciseDefinition.swift
        group: Shared/Domain
      - path: Domain/Models/WorkoutActivityType.swift
        group: Shared/Domain
      - path: Domain/Models/BodyPart.swift
        group: Shared/Domain
      - path: Domain/Models/InjurySeverity.swift
        group: Shared/Domain
      - path: Domain/Models/InjuryInfo.swift
        group: Shared/Domain
      - path: Domain/Models/HabitType.swift
        group: Shared/Domain
      - path: Domain/Models/CardioSecondaryUnit.swift
        group: Shared/Domain
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.raftel.dailve.watchkitapp
        PRODUCT_NAME: DUNEWatch
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "0.1.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_FILE: ../DUNEWatch/Resources/Info.plist
        INFOPLIST_KEY_CFBundleIconName: AppIcon
        INFOPLIST_KEY_CFBundleDisplayName: DUNE
        WATCHOS_DEPLOYMENT_TARGET: "26.0"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        DEVELOPMENT_TEAM: "4GWU9QB2JZ"
        CODE_SIGN_IDENTITY: "Apple Development"
        INFOPLIST_KEY_WKCompanionAppBundleIdentifier: com.raftel.dailve
        INFOPLIST_KEY_NSHealthShareUsageDescription: "DUNE needs access to your health data to track heart rate during workouts."
        INFOPLIST_KEY_NSHealthUpdateUsageDescription: "DUNE records your workout data to Health."
        CODE_SIGN_ENTITLEMENTS: ../DUNEWatch/DUNEWatch.entitlements
    entitlements:
      path: ../DUNEWatch/DUNEWatch.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.raftel.dailve
        com.apple.developer.icloud-services:
          - CloudKit
    dependencies:
      - sdk: HealthKit.framework
      - sdk: WatchConnectivity.framework

  DUNETests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ../DUNETests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.raftel.dailve.tests
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/DUNE.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/DUNE"
        BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: DUNE

  DUNEUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: ../DUNEUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.raftel.dailve.uitests
        GENERATE_INFOPLIST_FILE: true
        TEST_TARGET_NAME: DUNE
    dependencies:
      - target: DUNE
